Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_day1.Models;
using MVC_day1.ViewModel;

namespace MVC_day1.Controllers
{
    public class CourseController : Controller
    {
        Intelligent db = new Intelligent();

        [Route("/Courses")]
        public IActionResult GetAll()
        {
            var courses = db.Courses.ToList();
            return View(courses);
        }

        [Route("/Courses/{id}")]
        public IActionResult Details(int id)
        {
            var courses = db.Courses
                .Where(c => c.Id == id)
                .Include(c => c.Instructors)
                .Select(c => new CourseViewModelVM
                {
                    CourseName = c.Name,
                    Department = c.Departments.Name,
                    minDegree = c.MinDegree,
                    instructors = db.Instructors
                    .Where(i => i.Course_id == id)
                    .Select(i => new InstructorViewModelVM
                    {
                        Name = i.Name,
                        Address = i.Address,
                        image = i.Image
                    })
                    .ToList(),
                    trainees = db.Crs_Results
                    .Where(t => t.Course_id == id)
                    .Include(t => t.Trainees)
                    .Select(t => new TraineeViewModel
                    {
                        Name = t.Trainees.Name
                    })
                    .ToList(),
                })
                .FirstOrDefault();
            return View(courses);
        }

      
        public IActionResult Delete(int id)
        {
            var course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("GetAll");
        }
        [HttpGet]
        [Route("/CourseA")]
        public IActionResult InsertCourse()
        {
            var Depts = db.Departments.ToList();
            ViewBag.Departments = Depts;
            return View();
        }
        [HttpPost]
        public IActionResult AddCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var Depts = db.Departments.ToList();
            ViewBag.Departments = Depts;
            return View("InsertCourse", course);
        }

        [Route("/CourseU/{id}")]
        public IActionResult Update(int id)
        {
            var course = db.Courses.Find(id);
            var Depts = db.Departments.ToList();
            ViewBag.Departments = Depts;
            return View(course);
        }

        public IActionResult SaveUpdate(Course c)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Update(c);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var Depts = db.Departments.ToList();
            ViewBag.Departments = Depts;
            return View("Update", c);
        }
    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_day1.Models;
using MVC_day1.ViewModel;
using System.Runtime.Intrinsics.Arm;
namespace MVC_day1.Controllers
{
    public class DepartmentController : Controller
    {
        Intelligent db = new Intelligent();

        [Route("/Depts")]
        public IActionResult GetAll()
        {
            var depts = db.Departments.ToList();
            return View(depts);
        }
		[Route("/Depts/{id}")]
		public IActionResult Details(int id)
        {
            var dept = db.Departments
                .Where(d => d.Dept_id == id)
                .Select(d => new DeptViewModelVM
                {
                    Name = d.Name,
                    Manager = d.Manager,
                    Instructor = db.Instructors.Where(i => i.Dept_id == id).Select(i => new InstructorViewModelVM { Name = i.Name, Address = i.Address }).ToList(),
                    Trainee_Name = db.Trainees.Where(i => i.Dept_id == id).Select(i => i.Name).ToList(),
                    Course_Name = db.Courses.Where(i => i.Dept_id == id).Select(i => i.Name).ToList(),

                })
                .FirstOrDefault();
            return View(dept);
        }
		[Route("/DeptsA")]
		public IActionResult InsertDept()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNew(Department dept)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(dept);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View("InsertDept", dept);
        }
		[Route("/DeptsU/{id}")]
		public IActionResult Update(int id)
        {
            var dept = db.Departments.Find(id);
            return View(dept);
        }

        [HttpPost]
        public IActionResult SaveUpdate(Department dept)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Update(dept);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View("Update", dept);
        }
        public IActionResult Delete(int id)
        {
            var dept = db.Departments.Find(id);
            var course = db.Courses.Where(c => c.Dept_id == id).ToList(); 
            var ins = db.Instructors.Where(i => i.Dept_id == id).FirstOrDefault();
            var trainee = db.Trainees.Where(t => t.Dept_id == id).ToList();

            foreach (var item in trainee)
            {
                if (trainee != null)
                {
                    foreach (var C in course)
                    {
                        if (course != null)
                        {
                            var crs = db.Crs_Results.Where(c => c.Trainee_id == item.Id && c.Course_id == C.Id).FirstOrDefault();
                            db.Crs_Results.Remove(crs);
                            db.Trainees.Remove(item);
                            db.Courses.Remove(C);
                        }
                        else
                        {
                            var crs = db.Crs_Results.Where(c => c.Trainee_id == item.Id).FirstOrDefault();
                            db.Crs_Results.Remove(crs);
                            db.Trainees.Remove(item);
                        }
                    }
                   
                }
            }
           
            if( ins != null )
            {
                db.Instructors.Remove(ins);
            }

            db.Departments.Remove(dept);
            db.SaveChanges();
            return RedirectToAction("GetAll");
        }

        //public IActionResult GetResults(int id)
        //{
        //    var dept = db.Departments
        //        .Where(d => d.Dept_id == id)
        //        .Select(d => new DeptViewModelVM
        //        { 
        //            Course = ed.Courses.Where(c=>c.Dept_id == id).Select(c=> new CourseViewModelVM 
        //            {
        //                CourseName = c.
        //            }).ToList(),
        //        })
        //        .FirstOrDefault();
        //    return View(dept);
        //}
    }
}

Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_day1.Models;

namespace MVC_day1.Controllers
{
    public class InstructorController : Controller
    {
        Intelligent db = new Intelligent();


        public IActionResult HomePage() 
        { return View(); }
		public IActionResult Contact()
		{ return View(); }

        [Route("/Ins")]

        public IActionResult GetAll()
        {
            var instructors = db.Instructors.ToList();
            return View(instructors);
        }
		[Route("/Ins/{id}")]
		public IActionResult Details(int id) 
        {
            var instructors = db.Instructors.Include(i => i.Departments).Include(i=>i.Courses).FirstOrDefault(i => i.Id == id);
                return View(instructors);
        }
        [HttpGet]
		[Route("/InsA")]
		public IActionResult InsertInstructor() 
        {
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
            var courses = db.Courses.ToList();
            ViewBag.Courses = courses;  
			return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddInstructorAsync(Instructor ins) 
        {
            if (ModelState.IsValid) 
            {
                bool isUnique = await db.IsObjectUniqueAsync(ins);
                if (isUnique) 
                {
                    db.Instructors.Add(ins);
                    await db.SaveChangesAsync();
                    return RedirectToAction("GetAll");
                }
                else
                {
                    ModelState.AddModelError("", "This Instructor Already Exists.");
                }
            }
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            var courses = db.Courses.ToList();
            ViewBag.Courses = courses;
            return View("InsertInstructor");
        }

        public IActionResult Delete(int id) 
        {
            var ins = db.Instructors.Find(id);
            db.Instructors.Remove(ins);
            db.SaveChanges();
            return RedirectToAction("GetAll");
        }
		[Route("/InsU/{id}")]
		public IActionResult Update(int id) 
        {
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
            var courses = db.Courses.ToList();
            ViewBag.Courses = courses;
            var ins = db.Instructors.Find(id);
            return View(ins);
        }

        [HttpPost]
        public IActionResult SaveUpdate(Instructor ins) 
        {
            if (ModelState.IsValid) 
            {
                db.Instructors.Update(ins);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
			var depts = db.Departments.ToList();
			ViewBag.Departments = depts;
            var courses = db.Courses.ToList();
            ViewBag.Courses = courses;
            return View("Update", ins);
		}

    }
}

Controllers/TraineeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_day1.Models;
using MVC_day1.ViewModel;

namespace MVC_day1.Controllers
{
    public class TraineeController : Controller
    {
        Intelligent db = new Intelligent();
        [Route("/Trainee")]
        public IActionResult GetAll()
        {
            var students = db.Trainees.ToList();
            return View(students);
        }
		[Route("/TraineeD/{id}")]
        public IActionResult Details(int id)
        {
            var trainees = db.Trainees.Where(t => t.Id == id)
                .Select(t => new TraineeViewModel
                {
                    Name = t.Name,
                    image = t.image,
                    Department = t.Departments.Name,
                    Courses = db.Crs_Results.Where(t => t.Trainee_id == id)
                    .Include(c => c.Course)
                    .Select(c => new CourseViewModelVM
                    {
                        CourseName = c.Course.Name,
                        minDegree = c.Course.MinDegree,
                        Grade = c.Degree,
                        color = c.Degree < c.Course.MinDegree ? "color:red;" : "color:green;"

                    })
                    .ToList(),
                })
                .FirstOrDefault();
            return View(trainees);
        }

        [HttpPost]
        public async Task<IActionResult> AddTraineeAsync(Trainee t)
        {
            if (ModelState.IsValid)
            {
                bool isUnique = await db.IsObjectUniqueAsync(t);
                if (isUnique)
                {
                    db.Trainees.Add(t);
                    await db.SaveChangesAsync();
                    return RedirectToAction("GetAll");
                }
                else 
                {
                    ModelState.AddModelError("", "This Trainee Already exists.");
                }
                
            }
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            return View("InsertTrainee", t);
        }
		[Route("/TraineeA")]
		public IActionResult InsertTrainee()
        {
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            return View();
        }
		[Route("/TraineeU/{id}")]
		public IActionResult Update(int id)
        {
            var trainee = db.Trainees.Find(id);
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            return View(trainee);
        }
        [HttpPost]
		
		public IActionResult SaveUpdate(Trainee t)
        {
            if (ModelState.IsValid)
            {
                db.Trainees.Update(t);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            var depts = db.Departments.ToList();
            ViewBag.Departments = depts;
            return View("update", t);
        }

        public IActionResult Delete(int id)
        {
            var trainee = db.Trainees.Find(id);
            db.Trainees.Remove(trainee);
            db.SaveChanges();
            return RedirectToAction("GetAll");
        }

        public IActionResult GetAll_results()
        {
            var students = db.Trainees.ToList();
            return View(students);
        }


    }
}

Views/Shared/_Advance.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Mentor </title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="/assets/img/favicon.png" rel="icon">
  <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="/assets/css/main.css" rel="stylesheet">
</head>

<body class="starter-page-page">

  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="index.html" class="logo d-flex align-items-center me-auto">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="/assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Education</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="/Instructor/HomePage">Home</a></li>
          <li><a asp-action="GetAll" asp-controller="Instructor">Instructors</a></li>
          <li><a asp-action="GetAll" asp-controller="Course">Courses</a></li>
          <li><a asp-action="GetAll" asp-controller="Trainee">Trainees</a></li>
          <li><a asp-action="GetAll" asp-controller="Department">Departments</a></li>
          <li class="dropdown"><a href="#"><span>New</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a asp-action="InsertInstructor" asp-controller="Instructor">Add Instructor</a></li>
              <li><a asp-action="InsertTrainee" asp-controller="Trainee">Add Trainee</a></li>
             <li><a asp-action="InsertCourse" asp-controller="Course">Add Course</a></li>
              <li><a asp-action="InsertDept" asp-controller="Department">Add Department</a></li>
            </ul>
          </li>
          <li><a asp-action="Contact" asp-controller="Instructor">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </header>

  <main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            @RenderSection("DetailedTitle",false)
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
      @RenderSection("Back",false)
      </nav>
    </div><!-- End Page Title -->

    <!-- Starter Section Section -->
    <section id="starter-section" class="starter-section section">

            @RenderBody()

    </section><!-- /Starter Section Section -->

  </main>

  <footer id="footer" class="footer position-relative light-background">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="logo d-flex align-items-center">
            <span class="sitename">Mentor</span>
          </a>
          <div class="footer-contact pt-3">
            <p>Tahrir Square</p>
            <p>Cairo, 535022</p>
            <p class="mt-3"><strong>Phone:</strong> <span>+2001120548933</span></p>
            <p><strong>Email:</strong> <span>info@example.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-12 footer-newsletter">
          <h4>Our Newsletter</h4>
          <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
          <form action="forms/newsletter.php" method="post" class="php-email-form">
            <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your subscription request has been sent. Thank you!</div>
          </form>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Mentor</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/assets/vendor/php-email-form/validate.js"></script>
  <script src="/assets/vendor/aos/aos.js"></script>
  <script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="/assets/vendor/swiper/swiper-bundle.min.js"></script>

  <!-- Main JS File -->
  <script src="/assets/js/main.js"></script>

</body>

</html>
@RenderSection("scripts", false)

Views/Shared/_CourseLay.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Mentor</title>
  <meta name="description" content="">
  <meta name="keywords" content="">


  <!-- Favicons -->
  <link href="/assets/img/favicon.png" rel="icon">
  <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="/assets/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Mentor
  * Template URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="courses-page">

  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="index.html" class="logo d-flex align-items-center me-auto">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="/assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Mentor</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
            <li><a href="/Instructor/HomePage">Home</a></li>
            <li><a asp-action="GetAll" asp-controller="Instructor">Instructors</a></li>
            <li><a asp-action="GetAll" asp-controller="Course">Courses</a></li>
            <li><a asp-action="GetAll" asp-controller="Trainee">Trainees</a></li>
            <li><a asp-action="GetAll" asp-controller="Department">Departments</a></li>
          <li class="dropdown"><a href="#"><span>New</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a asp-action="InsertInstructor" asp-controller="Instructor">Add Instructor</a></li>
              <li><a asp-action="InsertTrainee" asp-controller="Trainee">Add Trainee</a></li>
             <li><a asp-action="InsertCourse" asp-controller="Course">Add Course</a></li>
              <li><a asp-action="InsertDept" asp-controller="Department">Add Department</a></li>
            </ul>
          </li>
          <li><a asp-action="Contact" asp-controller="Instructor">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>

  <main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Courses</h1>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        @RenderSection("Back",false)
      </nav>
    </div><!-- End Page Title -->

    <!-- Courses Section -->
    <section id="courses" class="courses section">

      <div class="container">

        <div class="row">

                    @RenderBody()

        </div>

      </div>

    </section><!-- /Courses Section -->

  </main>

  <footer id="footer" class="footer position-relative light-background">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="logo d-flex align-items-center">
            <span class="sitename">Mentor</span>
          </a>
          <div class="footer-contact pt-3">
            <p>A108 Adam Street</p>
            <p>New York, NY 535022</p>
            <p class="mt-3"><strong>Phone:</strong> <span>+1 5589 55488 55</span></p>
            <p><strong>Email:</strong> <span>info@example.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-12 footer-newsletter">
          <h4>Our Newsletter</h4>
          <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
          <form action="forms/newsletter.php" method="post" class="php-email-form">
            <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your subscription request has been sent. Thank you!</div>
          </form>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Mentor</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/assets/vendor/php-email-form/validate.js"></script>
  <script src="/assets/vendor/aos/aos.js"></script>
  <script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="/assets/vendor/swiper/swiper-bundle.min.js"></script>

  <!-- Main JS File -->
  <script src="/assets/js/main.js"></script>

</body>

</html>