Models/Crs_result.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_day1.Models
{
    public class Crs_result
    {
        [Key]
        public int Id { get; set; }
        public int Degree { get; set; }

        [ForeignKey("Course")]
        [DisplayName("Course Name")]
        public int? Course_id { get; set; }

        [ForeignKey("Trainees")]
        [DisplayName("Trainee Name")]
        public int? Trainee_id { get; set; }

        
        public Course? Course { get; set; }

        public Trainee? Trainees { get; set; }
    }
}

Controllers/Crs_resultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_day1.Models;
using System.Diagnostics;

namespace MVC_day1.Controllers
{
	public class Crs_resultController : Controller
	{
        Intelligent db = new Intelligent();

		public IActionResult InsertResult()
		{
			var trainees = db.Trainees.ToList();
			var courses = db.Courses.ToList();
			ViewBag.Trainees = trainees;
			ViewBag.Courses = courses;
			return View();
		}
		[HttpPost]
		public IActionResult AddResult(Crs_result res)
		{
			if (ModelState.IsValid)
			{
				db.Crs_Results.Add(res);
				db.SaveChanges();
				return RedirectToAction("GetAll", "Trainee");
			}
			var trainees = db.Trainees.ToList();
			var courses = db.Courses.ToList();
			ViewBag.Trainees = trainees;
			ViewBag.Courses = courses;
			return View("InsertResult", res);
		}







		public IActionResult Update(string name)
		{
			var courses = db.Courses.ToList();
			ViewBag.Courses = courses;
			var trainees = db.Trainees.ToList();
			ViewBag.Trainees = trainees;
			var result = db.Crs_Results.Find(name);
			return View(result);
		}

		public IActionResult SaveUpdate(Crs_result crs)
		{
			if (ModelState.IsValid)
			{
				db.Crs_Results.Update(crs);
				db.SaveChanges();
				return RedirectToAction("GetResults", "Department");
			}
			var courses = db.Courses.ToList();
			ViewBag.Courses = courses;
			var trainees = db.Trainees.ToList();
			ViewBag.Trainees = trainees;
			return View("Update", crs);

		}
	}
}

Views/Crs_result/InsertResult.cshtml
@model Crs_result 

@{
	
	SelectList Courses = new SelectList(ViewBag.Courses, "Id", "Name");
	SelectList Trainess = new SelectList(ViewBag.Trainees, "Id", "Name");
}
<form method="post" asp-action="AddResult" asp-controller="Crs_result" >
	

	

	<label asp-for="@Model.Course_id"></label><br>
	<select asp-for="@Model.Course_id" asp-items="Courses"></select><br>

	<label asp-for="@Model.Trainee_id"></label><br>
	<select asp-for="@Model.Trainee_id" asp-items="Trainess"></select><br>
	

	<label asp-for="@Model.Degree"></label><br>
	<input asp-for="@Model.Degree" /><br>

	<button type="submit" class="btn btn-outline-primary">Add</button><br>
</form>

@section DetailedTitle{
		<div class="col-lg-8">
				  <h1>Results</h1>
	   </div>
}

Views/Crs_result/Insertion.cshtml

 <!--   


 
 <form method="post" asp-action="AddResult" asp-controller="Crs_result" >


     <label asp-for="Course_id"></label><br>
     <select asp-for="Course_id" asp-items="Courses"></select><br>


     <label asp-for="Degree"></label><br>
     <input asp-for="Degree" /><br>

     <button type="submit" class="btn btn-outline-primary">Add</button><br>
 </form>

 -->